version: 2
updates:
  # Maven updates for main branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"

  # Maven updates for main-lts branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main-lts"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:quarkus-bom"
      - dependency-name: "io.quarkus.platform:quarkus-bom"

  # GitHub Actions updates for main branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # GitHub Actions updates for main-lts branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main-lts"
